version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your pyproject.toml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
    rebase-strategy: "auto"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
