# yamllint configuration
# See https://yamllint.readthedocs.io/en/stable/rules.html

extends: default

rules:
  # Line length - allow longer lines for K8s manifests and URLs
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - 2 spaces, consistent
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Truthy values - allow various truthy values for K8s compatibility
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

  # Comments - require space after #
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # Braces - allow single-line with spaces
  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Brackets - allow single-line with spaces
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Document markers
  document-start: disable
  document-end: disable

  # Key duplicates
  key-duplicates: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # Trailing spaces
  trailing-spaces: enable

# Ignore patterns
ignore:
  - "*.gotmpl"
  - "**/templates/**"
  - "**/.venv/**"
  - "**/venv/**"
  - "**/node_modules/**"
