labels: [idea]

body:
  - type: markdown
    attributes:
      value: |
        Share your ideas for new features or improvements to the Recipe Scraper Service!

  - type: textarea
    id: idea
    attributes:
      label: Idea Description
      description: Describe your idea for a new feature or improvement
      placeholder: What if the service could...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this solve? What use case does it address?
      placeholder: This would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
      placeholder: It could work by...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or mockups
      placeholder: Here's an example...
