---
title: "[Idea] "
labels:
  - idea
body:
  - type: markdown
    attributes:
      value: |
        Share your ideas for improving the Recipe Scraper Service!

        For concrete feature requests, please use the [Feature Request issue template](../issues/new?template=feature_request.yml).

  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Describe your idea
      placeholder: What's your idea?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem It Solves
      description: What problem does this idea address?
      placeholder: Describe the problem this would solve

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: How might this be implemented?
      placeholder: Share any thoughts on implementation
