labels: [question]

body:
  - type: markdown
    attributes:
      value: |
        Ask questions about using the Recipe Scraper Service!

        Before asking, please:
        - Search existing discussions and issues
        - Check the documentation (README.md, API.md, SUPPORT.md)
        - Review the FAQ in SUPPORT.md

  - type: dropdown
    id: topic
    attributes:
      label: Topic Area
      description: What is your question about?
      options:
        - Setup and Installation
        - API Usage
        - Recipe Scraping
        - Nutritional Analysis
        - Spoonacular Integration
        - Database Configuration
        - Deployment
        - Performance
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to accomplish
      placeholder: I'm trying to... but I'm getting...

  - type: textarea
    id: config
    attributes:
      label: Relevant Configuration
      description: Share relevant configuration (redact secrets!)
      placeholder: |
        Python version: 3.13
        Deployment: Docker
        etc.
