---
# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-scraper
  namespace: recipe-scraper
  annotations:
    # Ignoring image tag and pull policy checks since we build images locally
    kube-score/ignore: container-image-tag,container-image-pull-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-scraper
  template:
    metadata:
      labels:
        app: recipe-scraper
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - recipe-scraper
                topologyKey: kubernetes.io/hostname
      containers:
        - name: recipe-scraper
          image: recipe-scraper-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: RECIPE_SCRAPER_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: RECIPE_SCRAPER_DB_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: POSTGRES_PORT
            - name: POSTGRES_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: POSTGRES_SCHEMA
            - name: RECIPE_SCRAPER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-scraper-secrets
                  key: RECIPE_SCRAPER_DB_PASSWORD
            - name: KROGER_API_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: KROGER_API_CLIENT_ID
            - name: KROGER_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: recipe-scraper-secrets
                  key: KROGER_API_CLIENT_SECRET
            - name: SPOONACULAR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: recipe-scraper-secrets
                  key: SPOONACULAR_API_KEY
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: REDIS_PORT
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: recipe-scraper-config
                  key: REDIS_DB
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-scraper-secrets
                  key: REDIS_PASSWORD
          livenessProbe:
            httpGet:
              path: /api/liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/readiness
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: logs-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
