---
# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-ingress
  namespace: recipe-scraper
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: recipe.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: recipe-scraper
                port:
                  number: 8000
