---
# k8s/pod-disruption-budget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: recipe-scraper-pdb
  namespace: recipe-scraper
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: recipe-scraper
