---
name: Feature Request
description: Propose a new feature or enhancement for the recipe scraper service
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - jsamuelsen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new feature! Please fill out the form below
        to help us understand your request and evaluate its implementation.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: "I'm trying to do X, but the service doesn't support Y..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: "Add a new endpoint that allows users to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches or solutions have you considered?
      placeholder: "I also considered..."
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area of the service would this feature affect?
      options:
        - Recipe Scraping Engine
        - Web Scraper (Popular Recipes)
        - Spoonacular Integration
        - Nutritional Analysis
        - Recipe Recommendations
        - API Endpoints
        - Database Models
        - Cache Layer
        - Background Tasks
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Important for common use cases)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case Description
      description: Describe a specific use case or scenario where this feature would be useful
      placeholder: "As a user, I want to... so that I can..."
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (if applicable)
      description: If this involves API changes, provide a proposed API design
      placeholder: |
        POST /api/v1/recipes/batch-scrape
        Request:
        {
          "urls": ["url1", "url2"]
        }
        Response:
        {
          "recipes": [...]
        }

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature may introduce breaking changes to existing APIs
          required: false
        - label: This feature requires database schema changes
          required: false
        - label: This feature requires configuration changes
          required: false

  - type: textarea
    id: breaking_details
    attributes:
      label: Breaking Change Details
      description: If this introduces breaking changes, describe them and potential migration paths
      placeholder: "This would change the response structure for..."

  - type: checkboxes
    id: security
    attributes:
      label: Security Implications
      description: Does this feature have security implications?
      options:
        - label: This feature may have security implications
          required: false

  - type: textarea
    id: security_details
    attributes:
      label: Security Details
      description: If there are security implications, describe them
      placeholder: "This feature would require authentication because..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, diagrams, or examples
      placeholder: "Here's a mockup of how this could work..."

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true
        - label: I am willing to help test this feature if implemented
          required: false
