---
name: Security Vulnerability (Low Severity)
description: Report a LOW severity security issue (use Security Advisories for critical/high issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - jsamuelsen
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: For Critical or High Severity Issues

        **DO NOT** use this template for critical or high severity security vulnerabilities!

        Instead, report them privately via GitHub Security Advisories:
        https://github.com/Recipe-Web-App/recipe-scraper-service/security/advisories/new

        This template is ONLY for **low severity** security issues that do not pose
        an immediate threat.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: Confirm this is a LOW severity issue (if not, use Security Advisories!)
      options:
        - Low (Minor security concern, no immediate threat)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security issue
      placeholder: Describe the security concern
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Missing Security Headers
        - Information Disclosure (non-sensitive)
        - Security Misconfiguration
        - Verbose Error Messages
        - Weak Cryptography
        - Insecure Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact of this security issue?
      placeholder: "An attacker could potentially..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce or verify the security issue
      placeholder: |
        1. Send request to '...'
        2. Observe response headers
        3. Note missing security header
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - Recipe Scraping Engine
        - API Endpoints
        - Authentication/Authorization
        - Database Layer
        - Cache Layer
        - Middleware
        - Third-party Integrations
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: Do you have a suggestion for how to fix this?
      placeholder: "This could be fixed by..."

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Acknowledgment of responsible disclosure
      options:
        - label: I understand this is a low severity issue and agree to public disclosure
          required: true
        - label: I have not and will not exploit this vulnerability
          required: true
        - label: I have not shared this vulnerability publicly before reporting it
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information about the security issue
      placeholder: Any other relevant details
