---
name: Task
description: Track development tasks, work items, and planned implementation work
title: "[Task]: "
labels: ["task", "needs-triage"]
assignees:
  - jsamuelsen
body:
  - type: markdown
    attributes:
      value: |
        Use this template to track development tasks, work items, and planned
        implementation work.

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Describe the task to be completed
      placeholder: "Implement..."
    validations:
      required: true

  - type: dropdown
    id: task_type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Implementation (New Feature)
        - Refactoring
        - Technical Debt
        - Testing
        - Documentation
        - Infrastructure
        - Configuration
        - Dependency Update
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area of the service does this task affect?
      options:
        - Recipe Scraping Engine
        - Web Scraper (Popular Recipes)
        - Spoonacular Integration
        - Nutritional Analysis
        - Recipe Recommendations
        - API Endpoints
        - Database Models
        - Cache Layer
        - Background Tasks
        - Testing Infrastructure
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this task?
      options:
        - Critical (Urgent)
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What must be completed for this task to be considered done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing Requirements
      description: What testing is required for this task?
      placeholder: |
        - Unit tests for new functions
        - Integration tests for API endpoints
        - Manual testing of scraping behavior
    validations:
      required: true

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Technical notes, considerations, or implementation details
      placeholder: |
        - Use SQLAlchemy ORM for database queries
        - Follow existing pattern in recipe_service.py
        - Update API documentation

  - type: textarea
    id: related
    attributes:
      label: Related Issues/PRs
      description: Link to related issues or pull requests
      placeholder: |
        Related to #123
        Depends on #456

  - type: textarea
    id: estimated_effort
    attributes:
      label: Estimated Effort
      description: Rough estimate of effort required (optional)
      placeholder: "Small (< 1 day), Medium (1-3 days), Large (> 3 days)"

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: Impact
      description: Does this task involve breaking changes or significant impacts?
      options:
        - label: This task may introduce breaking changes
          required: false
        - label: This task requires database migration
          required: false
        - label: This task affects external APIs
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about this task
      placeholder: Any additional details or context
