# Web scraper configuration for recipe extraction
# Contains word lists and extraction parameters

# Category patterns to detect (regex patterns for category detection)
category_patterns:
  - "^[a-zA-Z\\s]+s$"  # Simple plurals (including multi-word)
  - "^[a-zA-Z\\s]+ & [a-zA-Z\\s]+$"  # Patterns like "soups & stews"
  - "^[a-zA-Z\\s]+ and [a-zA-Z\\s]+$"  # Patterns like "meat and poultry"
  - ".*\\brecipes\\b.*"  # Anything containing "recipes"
  - ".*\\bideas\\b.*"  # Anything containing "ideas"
  - ".*\\bcooking\\b.*"  # Anything containing "cooking"
  - ".*\\bcuisine\\b.*"  # Anything containing "cuisine"
  - ".*\\bstyle\\b.*"  # Anything containing "style"
  - ".*\\bdishes\\b.*"  # Anything containing "dishes"
  - "^all\\b.*"  # Things starting with "all"
  - "^best\\b.*"  # Things starting with "best"
  - "^top\\b.*"  # Things starting with "top"
  - "^\\d+.*\\brecipes\\b.*"  # Numbers + recipes
  - "^\\d+.*\\bcocktails\\b.*"  # Numbers + cocktails like "41 spring cocktails"
  - "^\\d+.*\\bdrinks\\b.*"  # Numbers + drinks
  - "^\\d+.*\\bof\\s+the\\s+best\\b.*"  # "10 of the best juicers"
  - ".*\\bmust-haves\\b.*"  # "pie must-haves"
  - ".*\\bperfection\\b.*"  # "pizza perfection"
  - ".*\\btonight\\b.*"  # "chicken tonight"
  - ".*\\bpolicy\\b.*"  # "cookies policy"
  - ".*\\bcollections?\\b.*"  # Category collections
  - "^what to\\b.*"  # "what to eat and drink"
  - "^how to\\b.*"  # "how to make"
  - ".*\\bfor\\s+(sunny\\s+days|fourth\\s+of\\s+july|right\\s+now)\\b.*"  # Seasonal
  - ".*\\bclub\\b.*"  # "cooking club"
  - "^quick\\s+bread\\b.*"  # "quick bread recipes"

# Single word categories to filter out
single_word_categories:
  - "appetizers"
  - "desserts"
  - "salads"
  - "soups"
  - "drinks"
  - "sides"
  - "entrees"
  - "mains"
  - "snacks"
  - "beverages"
  - "breads"
  - "cakes"
  - "cookies"
  - "pies"
  - "pastries"
  - "casseroles"
  - "sandwiches"
  - "wraps"
  - "burgers"
  - "pizzas"
  - "pastas"
  - "noodles"
  - "rice"
  - "grains"
  - "vegetables"
  - "fruits"
  - "meats"
  - "poultry"
  - "seafood"
  - "fish"
  - "steaks"
  - "chops"
  - "roasts"
  - "stews"
  - "curries"
  - "tacos"
  - "burritos"
  - "quesadillas"
  - "enchiladas"
  - "nachos"
  - "bread"
  - "cake"
  - "cookie"
  - "pie"
  - "pizza"
  - "pasta"
  - "candy"
  - "vanilla"
  - "chocolate"
  - "cheese"
  - "cheesecake"
  - "savory"

# Category indicators for compound category detection
category_indicators:
  - "syrup"
  - "flour"
  - "extract"
  - "powder"
  - "spice"
  - "herb"
  - "tonight"
  - "corner"
  - "perfection"
  - "must-haves"
  - "resources"

nav_prefixes:
  - "all "
  - "new "
  - "best "
  - "top "
  - "most "
  - "popular "
  - "featured "

# Keywords to exclude from URLs (navigation, admin, category pages)
url_exclude_keywords:
  - "login"
  - "logout"
  - "register"
  - "account"
  - "auth"
  - "sign-in"
  - "sign-up"
  - "favorites"
  - "collections"
  - "my-recipes"
  - "recipe-box"
  - "saved"
  - "subscribe"
  - "newsletter"
  - "magazine"
  - "shop"
  - "cart"
  - "checkout"
  - "about"
  - "contact"
  - "privacy"
  - "terms"
  - "help"
  - "faq"
  - "category"
  - "categories"
  - "index"
  - "all-recipes"
  - "recipe-index"
  - "search"
  - "filter"
  - "sort"
  - "browse"
  - "cooking-style"
  - "meal-types"
  - "techniques"
  - "ingredients"
  - "cuisine"
  - "diet"
  - "holiday"
  - "season"
  - "breakfast"
  - "lunch"
  - "dinner"
  - "dessert"
  - "appetizer"
  - "snack"
  - "vegan"
  - "vegetarian"
  - "gluten-free"
  - "dairy-free"
  - "healthy"
  - "facebook"
  - "twitter"
  - "instagram"
  - "pinterest"
  - "youtube"
  - "social"
  - "app"
  - "mobile"
  - "download"
  - "subscribe"
  - "gift"
  - "bundle"
  - "show"
  - "collection"
  - "round-up"
  - "guide"
  - "tips"
  - "how-to"
  - "what-to"
  - "brand"
  - "new"
  - "trending"
  - "popular"
  - "featured"
  - "editor"
  - "most-saved"
  - "most-popular"
  - "best-of"
  - "top-"
  - "gallery"
  # Category page patterns
  - "/recipes/"
  - "/category/"
  - "/categories/"
  - "/collection/"
  - "/collections/"
  - "/dishes-beverages/"
  - "/meat-and-poultry/"
  - "/soups-stews-and-chili/"
  - "/pasta-and-noodles/"
  - "/desserts/"
  - "/cookies-bars"
  - "/muffins-popovers"
  - "/pancakes-waffles"
  - "/biscuits-shortcakes"
  - "/brownies-bars"
  - "/ice-cream-frozen-treats"
  - "/cupcakes"
  - "/coffee-cake"
  - "/cheesecake"
  - "/resources/"
  - "-recipes/"
  - "-recipe/"

# Recipe names to exclude (navigation and UI elements)
exclude_names:
  - "log in"
  - "log out"
  - "login"
  - "logout"
  - "register"
  - "sign in"
  - "sign up"
  - "my account"
  - "account"
  - "profile"
  - "settings"
  - "preferences"
  - "favorites"
  - "saved"
  - "my recipes"
  - "recipe box"
  - "collections"
  - "subscribe"
  - "newsletter"
  - "magazine"
  - "shop"
  - "cart"
  - "buy now"
  - "download"
  - "app"
  - "mobile"
  - "get the app"
  - "follow us"
  - "facebook"
  - "twitter"
  - "instagram"
  - "pinterest"
  - "youtube"
  - "about"
  - "contact"
  - "help"
  - "faq"
  - "privacy"
  - "terms"
  - "recipes"
  - "all recipes"
  - "recipe index"
  - "browse"
  - "search"
  - "categories"
  - "breakfast"
  - "lunch"
  - "dinner"
  - "dessert"
  - "appetizer"
  - "vegan"
  - "vegetarian"
  - "gluten-free"
  - "healthy"
  - "easy"
  - "quick"
  - "one-pot"
  - "30-minute"
  - "low-carb"
  - "keto"
  - "spring"
  - "summer"
  - "fall"
  - "winter"
  - "holiday"
  - "christmas"
  - "thanksgiving"
  - "easter"
  - "new year"
  - "valentine"
  - "mother's day"
  - "father's day"
  - "july 4th"
  - "halloween"
  - "memorial day"
  - "what's new"
  - "trending"
  - "popular"
  - "featured"
  - "editor's pick"
  - "most saved"
  - "brand new"
  - "surprise me"
  - "recipe of the day"
  - "today's pick"
  - "unknown recipe"
  - "home"
  - "homepage"
  - "type"
  - "season"
  - "cuisine"
  - "diet"
  - "method"
  - "technique"
  # Category names that should be excluded - specific exact matches
  - "soups, stews & chili"  # Specific compound category name
  - "cookies & bars"  # Specific compound category name
  - "muffins & popovers"  # Specific compound category name
  - "pancakes & waffles"  # Specific compound category name
  - "biscuits & shortcakes"  # Specific compound category name
  - "brownies & bars"  # Specific compound category name
  - "ice cream & frozen treats"  # Specific compound category name
  - "cocktail corner"  # Specific navigation name
  - "blogger resources"  # Specific navigation name
  - "chicken mince"  # This is a specific ingredient category
  - "iced coffee recipes"  # Contains "recipes" but not caught by pattern
  - "drinks reviews"  # Contains "reviews"
  - "leftover chicken recipes"  # Contains "recipes"
  - "leftover rice recipes"  # Contains "recipes"
  - "leftover potato recipes"  # Contains "recipes"
  - "freezer-friendly pasta"  # Specific category description
  - "easy berry desserts for summer"  # Long category description
  - "satisfying vegan sandwiches, wraps & burgers for summer"  # Long category description
  - "coffee cake"  # Could be confused with actual recipes
  - "avocado"  # Single ingredient page

# Food indicators for recipe name validation
food_indicators:
  # Dishes and prepared foods
  - "soup"
  - "salad"
  - "sandwich"
  - "burger"
  - "pizza"
  - "pasta"
  - "noodles"
  - "rice"
  - "beans"
  - "lentils"
  - "quinoa"
  - "oats"
  - "bread"
  - "toast"
  - "pancakes"
  - "waffles"
  - "muffins"
  - "cookies"
  - "cake"
  - "pie"
  - "tart"
  - "cheesecake"
  - "brownies"
  - "bars"
  - "fudge"
  - "candy"
  - "ice cream"
  - "smoothie"
  - "juice"
  - "tea"
  - "coffee"
  - "cocktail"
  - "drink"
  # Proteins
  - "chicken"
  - "beef"
  - "pork"
  - "lamb"
  - "fish"
  - "salmon"
  - "tuna"
  - "shrimp"
  - "crab"
  - "lobster"
  - "tofu"
  - "tempeh"
  - "eggs"
  - "seafood"
  # Dairy and fats
  - "cheese"
  - "yogurt"
  - "milk"
  - "cream"
  - "butter"
  # Vegetables
  - "tomato"
  - "potato"
  - "onion"
  - "garlic"
  - "mushroom"
  - "pepper"
  - "carrot"
  - "broccoli"
  - "spinach"
  - "kale"
  - "avocado"
  - "corn"
  # Fruits
  - "apple"
  - "banana"
  - "berry"
  - "orange"
  - "lemon"
  - "lime"
  - "strawberry"
  - "blueberry"
  - "raspberry"
  # Flavors and sweeteners
  - "chocolate"
  - "vanilla"
  - "honey"
  - "maple"
  # Nuts and seeds
  - "peanut"
  - "almond"
  - "walnut"
  - "coconut"
  # Taste descriptors
  - "spicy"
  - "sweet"
  - "sour"
  - "savory"
  - "crispy"
  - "creamy"
  # Cooking methods
  - "grilled"
  - "baked"
  - "roasted"
  - "fried"
  - "steamed"
  - "sautéed"
