### Get nutritional info for a recipe
GET http://recipe.local/api/recipe-scraper/recipes/1/nutritional-info?include_total=true&include_ingredients=true
Accept: application/json

###

### Get nutritional info for an ingredient
GET http://recipe.local/api/recipe-scraper/ingredients/42/nutritional-info?quantity_value=100&measurement=gram
Accept: application/json
