### Create Recipe from URL
GET http://recipe.local/api/recipe-scraper/create-recipe?url=https://example.com/some-recipe
Accept: application/json

###

### Get Popular Recipes with Pagination
GET http://recipe.local/api/recipe-scraper/popular-recipes?limit=5&offset=5&count_only=false
Accept: application/json

###
