### Create Recipe from URL
POST http://recipe.local/api/recipe-scraper/create-recipe
Accept: application/json
Content-Type: application/json
X-User-Id: 11111111-1111-1111-1111-111111111111

{
  "recipeUrl": "https://www.allrecipes.com/cheesy-bacon-ranch-burger-sliders-11738006"
}

###

### Get Popular Recipes with Pagination
GET http://recipe.local/api/recipe-scraper/popular-recipes?limit=5&offset=5&count_only=false
Accept: application/json

###
