### Get Recommended Substitutions for Ingredient
GET http://recipe.local/api/recipe-scraper/ingredients/15/recommended-substitutions
Accept: application/json

###

### Get Pairing Suggestions for Recipe
GET http://recipe.local/api/recipe-scraper/recipes/3/pairing-suggestions
Accept: application/json

###
