name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: abatilo/actions-poetry@v4

      - name: Install dependencies
        run: poetry install

      - name: Run linting (ruff, docformatter, etc.)
        run: |
          poetry run ruff .
          poetry run docformatter --check --recursive .

      - name: Run tests with coverage
        run: poetry run pytest --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
