name: Cleanup

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete-branch:
    name: Delete Merged Branch
    runs-on: ubuntu-latest
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_branches: 'main,develop,staging,production'
          delete_tags: false
