name: Build Sphinx Docs

on:
  push:
    paths:
      - "docs/**"
      - "src/**"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "docs/**"
      - "src/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "1.8.2"

      - name: Install dependencies
        run: poetry install

      - name: Build docs
        run: poetry run sphinx-build -b html docs/source docs/build
