name: Check Links

on:
  push:
    branches: [main]
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  link-checker:
    name: Check Documentation Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links in markdown files
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: |
            --verbose
            --no-progress
            --exclude-path node_modules
            --exclude-path htmlcov
            --exclude-path .venv
            --exclude-private
            --accept 200,204,301,302,307,308,429
            --timeout 20
            --retry-wait-time 5
            --max-retries 3
            '**/*.md'
          fail: true

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🔗 Broken links detected in documentation';
            const body = `The link checker has found broken links in the documentation.

            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Please review and fix any broken links.`;

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'documentation,automated'
            });

            const existingIssue = issues.data.find(issue => issue.title === title);

            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['documentation', 'automated']
              });
            }
